name: Queens Dev News

on:
  schedule:
    # GitHub 使用 UTC；纽约 08:00 大致对应 12:00 UTC（夏令时）
    - cron: "0 12 * * *"     # 每天 08:00 NY
    - cron: "5 12 * * 1"     # 每周一 08:05 NY
  workflow_dispatch: {}

# 避免并发同时写同一个 Excel
concurrency:
  group: queens-dev-news-${{ github.ref_name }}
  cancel-in-progress: false

# 需要写权限才能 push
permissions:
  contents: write

jobs:
  run-daily:
    if: github.event.schedule == '0 12 * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # ✅ 必须：拿到完整历史，便于 rebase
          persist-credentials: true # 使用默认 GITHUB_TOKEN 推送

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily crawl (48h freshness)
        run: python run.py daily

      - name: Commit & push Excel (safe rebase)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/output/queens_dev_news.xlsx
          git commit -m "chore: update daily Queens dev news Excel [skip ci]" || echo "No changes"

          # ✅ 核心：推送前先把远端更新 rebase 进来，避免 non-fast-forward
          git pull --rebase origin "$BRANCH_NAME" || true

          # 推到当前分支
          git push origin HEAD:"$BRANCH_NAME"

  run-weekly:
    if: github.event.schedule == '5 12 * * 1' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly rollup (7d freshness)
        run: python run.py weekly

      - name: Commit & push Excel (safe rebase)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/output/queens_dev_news.xlsx
          git commit -m "chore: update weekly Queens rollup Excel [skip ci]" || echo "No changes"

          git pull --rebase origin "$BRANCH_NAME" || true
          git push origin HEAD:"$BRANCH_NAME"
