name: Queens Dev News

on:
  schedule:
    # GitHub cron 用的是 UTC 时间
    # 纽约早上 8:00 ≈ UTC 12:00（夏令时期间）
    - cron: "0 12 * * *"     # 每天 08:00 NY
    - cron: "5 12 * * 1"     # 每周一 08:05 NY
  workflow_dispatch: {}      # 手动触发

permissions:
  contents: write

jobs:
  run-daily:
    if: github.event.schedule == '0 12 * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 运行日更
        run: python run.py daily
      - name: 提交 Excel
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/output/queens_dev_news.xlsx
          git commit -m "update daily Queens dev news" || echo "No changes"
          git push

  run-weekly:
    if: github.event.schedule == '5 12 * * 1' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 运行周更
        run: python run.py weekly
      - name: 提交 Excel
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/output/queens_dev_news.xlsx
          git commit -m "update weekly Queens rollup" || echo "No changes"
          git push
