name: Queens Dev News

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"      # Daily at 08:00 New York
    - cron: "5 12 * * 1"      # Weekly Monday at 08:05 New York

permissions:
  contents: write

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run daily
        run: echo "✅ Daily workflow ran successfully"

  run-weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run weekly
        run: echo "✅ Weekly workflow ran successfully"



