name: Queens Dev News

on:
  workflow_dispatch: {}       # ✅ 手动运行按钮
  schedule:                   # ✅ 定时触发（UTC）
    - cron: "0 12 * * *"      # 每天 08:00 纽约时间（约等于 12:00 UTC，夏令时）
    - cron: "5 12 * * 1"      # 每周一 08:05 纽约时间（约等于 12:05 UTC）

concurrency:
  group: queens-dev-news-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  run-daily:
    # 手动触发时也允许跑 daily（方便测试）
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 12 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily crawl (48h freshness)
        run: python run.py daily

      - name: Show output tree
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la data || true
          ls -la data/output || true
          [ -f data/output/queens_dev_news.xlsx ] && echo "Excel exists." || echo "Excel NOT found."

      - name: Upload Excel artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: queens_dev_news.xlsx
          path: data/output/queens_dev_news.xlsx
          if-no-files-found: warn

      - name: Commit & push Excel (safe rebase)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f data/output/queens_dev_news.xlsx
          git commit -m "chore: update daily Queens dev news Excel [skip ci]" || echo "No changes"

          git pull --rebase origin "$BRANCH_NAME" || true
          git push origin HEAD:"$BRANCH_NAME"

  run-weekly:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '5 12 * * 1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Py


